version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superindo
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  app:
    build: .
    ports:
      - "6668:6668"
    environment:
      GRPC_PORT: 6668
      DATABASE_DSN: postgres://postgres:password@db:5432/superindo?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: ""
    depends_on:
      - db
      - redis
